# Generated by Django 2.0.2 on 2018-02-03 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('created_date', models.CharField(max_length=200)),
                ('webtoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtoon.Webtoon')),
            ],
        ),
    ]
